languageCode: en-us
title: Computational Biology Core
theme: gb-theme
permalinks:
  news: "/:year/:month/:slug/"
googleAnalytics: UA-115983496-1
outputs:
  home:
    - html
    - rss
    - json

enableRobotsTXT: true
DefaultContentLanguage: en
canonifyURLs: true
relativeURLs: true

pygmentsCodefences: true

params:
  acknowledgements: |
    Research reported on this website is supported by an Institutional Development
    Award (IDeA) from the National Institute of General Medical Sciences of the
    National Institutes of Health under grant number P20GM109035. 
# Menu
menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 2
  - identifier: support
    name: Support
    title: Support
    url: /support/
    weight: 3
  - identifier: services
    name: Services
    title: Services
    url: /services/
    weight: 4
  - identifier: resources
    name: Resources
    title: Resources
    url: /resources/
    weight: 5
  - identifier: blog
    name: Blog
    title: Blog
    url: https://medium.com/brown-compbiocore
    weight: 6
githubLink:
  cbcGithub: https://github.com/compbiocore/
# i18n
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/english

# Taxonomies
taxonomies:
  tag: "tags"
  type: "types"
  category: "category"
