#!/bin/bash
docker build --build-arg ORGANIZATION=$ORGANIZATION \
--build-arg GITHUB_USER=$GITHUB_USER \
--build-arg ACCESS_TOKEN=$ACCESS_TOKEN \
--build-arg EMBED_ROCKS_API_KEY=$EMBED_ROCKS_API_KEY \
--build-arg BASEURL=$BASEURL \
-t $IMAGE_NAME .
