name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: get embeds and github repos
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        EMBED_ROCKS_API_KEY: ${{ secrets.EMBED_ROCKS_API_KEY }}
      run: |
        npm install
        npm run data
    - name: Build Hugo
      uses: lowply/build-hugo@v0.58.3
      env:
        BASEURL: https://cbc-brown-edu.firebaseapp.com/
      with:
        args: --baseURL $BASEURL
    - name: Deploy to Firebase
      run: npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}
